steps:
  - name: 'gcr.io/$PROJECT_ID/pypi-tools:latest'
    id: 'sanity - print python version'
    entrypoint: 'python'
    args: ['--version']

  - name: 'gcr.io/$PROJECT_ID/pypi-tools:latest'
    id: 'build wheel'
    entrypoint: 'python'
    args: ['setup.py', 'bdist_wheel']
    dir: 'example-package'
    
artifacts:
  objects:
    location: 'gs://cloud-build-output/' 
    paths: ['dist/awesome_utility-0.0.1-py3-none-any.whl']
    
