steps:
  - name: 'gcr.io/$PROJECT_ID/pypi-tools:latest'
    id: 'sanity - print python version'
    entrypoint: 'python'
    args: ['--version']

  - name: 'gcr.io/$PROJECT_ID/pypi-tools:latest'
    id: 'build wheel'
    entrypoint: 'python'
    args: ['setup.py', 'bdist']
    
  - name: 'gcr.io/$PROJECT_ID/pypi-tools:latest'
    id: 'build dataroc image'
    args: ['/dataproc_image_build.sh']
    
artifacts:
  objects:
    location: 'gs://cloud-build-output/' 
    paths: ['dist/*']
